name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scala
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Build and test
        run: sbt -v +test

