name: CI

on:
  push:

jobs:
  test-scala:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build and test
        run: sbt +test
        working-directory: scala
  test-python:
    runs-on: ubuntu-20.04
    needs: test-scala
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.1"
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Package the artifact
        run: sbt +package
        working-directory: scala
      - name: Install Pip dependencies
        run: pip install -r requirements.txt
        working-directory: python
      - name: Run Python tests
        env:
          SCALA_PIT_JAR: ${{ github.workspace }}/scala/target/scala-2.12/spark-pit_2.12-0.1.0.jar
        run: SCALA_PIT_JAR=$SCALA_PIT_JAR python -m unittest discover -s tests
        working-directory: python
