name: Publish new version to PyPi

on: 
  workflow_dispatch:
    inputs: 
      bump_type:
        description: The type of version bump
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish-scala:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.1"
      
      - name: Install additional dependencies
        run: |
          pip install twine setuptools wheel

      - name: Set the new version number
        run: |
          python scripts/bump_version.py -t ${{ github.event.inputs.bump_type }} -e python

      - name: Get the new version number
        id: version
        run: |
          echo "::set-output name=pypi_version::$(cat scala/VERSION)"

      - name: Push updated version file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add python/VERSION
          git commit -m "Publish version ${{ steps.version.outputs.pypi_version }}"
          git push

      - name: Build the output file
        run: |
          python -m setup sdist bdist_wheel
        working-directory: python

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
        working-directory: python
