name: Publish new version

on: 
  workflow_dispatch:
    inputs: 
      bump_type:
        description: The type of version bump
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch


jobs:
  publish-scala:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          # TODO: Support more versions?
          java-version: 11
      
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.1"

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      
      - name: Set the new version number
        run: |
          python scripts/bump_version.py -t ${{ github.event.inputs.bump_type }} -e scala

      - name: Get the new version number
        id: version
        run: |
          echo "::set-output name=jar_version::$(cat scala/VERSION)"

      - name: Build artifact
        run: |
          sbt package        
        working-directory: scala
      
      - name: Push updated version file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scala/VERSION
          git commit -m "Release version ${{ steps.version.outputs.jar_version }}"
          git push

      - name: Create tag
        run: |
            tag=v${{ steps.version.outputs.jar_version }}
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git tag -a "${tag}" -m "Release version ${{ steps.version.outputs.jar_version }}"
            git push origin "${tag}"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.jar_version }}
          files: |
            LICENSE
            scala/target/scala-2.12/spark-pit_2.12-${{ steps.version.outputs.jar_version }}.jar
